source 'https://gemcutter.org'

gem "sinatra"
gem "sinatra-reloader"
gem "sinatra-flash"
gem "sinatra-namespace"
gem "sinatra-respond_to"
gem "dm-core"
gem "dm-migrations"
gem "dm-validations"
gem "dm-mysql-adapter"
gem "haml"
gem "sass"
gem "logger"
gem "bluecloth"
gem "twitter"
gem "carrierwave"
gem "carrierwave-datamapper", :require => 'carrierwave/datamapper'
gem "rmagick"
gem "json"
